force-app/main/default/objects/PBS_Savings_Account__c/PBS_Savings_Account__c.object-meta.xml
<CustomObject>
    <label>PBS Savings Account</label>
    <nameField>
        <label>Savings Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Savings Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Savings_Account__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <label>Customer Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PBS_Savings_Account__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <displayFormat>NR{0}</displayFormat>
    <label>Product Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PBS_Savings_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SavingsAccountController.cls
public with sharing class SavingsAccountController {
    @AuraEnabled
    public static PBS_Savings_Account__c getSavingsAccountData(String currentUserId) {
        PBS_Savings_Account__c savingsAccount = [SELECT Id, Name, Customer_Number__c, Current_Balance__c, Product_Code__c, CreatedById, Status__c, OwnerId FROM PBS_Savings_Account__c WHERE OwnerId =: currentUserId];
        return savingsAccount;
    }

    @AuraEnabled
    public static User getSavingsAccountHolder(String currentUserId) {
        User currentUser = [SELECT Name, Id FROM User WHERE Id =: currentUserId];
        return currentUser;
    }
}